# GitHub Actions Workflow responsible for cleaning up the template repository from
# the template-specific files and configurations. This workflow is supposed to be triggered automatically
# when a new template-based repository has been created.

name: Template Cleanup
run-name: ${{ github.actor }} is learning GitHub Templates
on:
  push:
    branches:
      - master

jobs:
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    if: github.event.repository.name == 'web-template-vue'
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      # Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install
      - run: yarn build
      - run: yarn lint
#
#      # Cleanup project
#      - name: Cleanup
#        run: ./gradlew templateCleanup
#      # Commit modified files
#      - name: Commit files
#        run: |
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add .
#          git commit -m "Template cleanup"
#      # Push changes
#      - name: Push changes
#        uses: ad-m/github-push-action@v0.6.0
#        with:
#          branch: main
#          github_token: ${{ secrets.GITHUB_TOKEN }}
